//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachHang
    {
        public int maKH { get; set; }
        public string tenKH { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Gmail { get; set; }
    
        public virtual tkUsers tkUsers { get; set; }
    }
}
