//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlBhEntities : DbContext
    {
        public qlBhEntities()
            : base("name=qlBhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HSX> HSX { get; set; }
        public virtual DbSet<newpro> newpro { get; set; }
        public virtual DbSet<sanPham> sanPham { get; set; }
        public virtual DbSet<TkAdmin> TkAdmin { get; set; }
        public virtual DbSet<tkUsers> tkUsers { get; set; }
        public virtual DbSet<DonHangRieng> DonHangRieng { get; set; }
        public virtual DbSet<donHang> donHang { get; set; }
        public virtual DbSet<khachHang> khachHang { get; set; }
        public virtual DbSet<tkNguoiDung> tkNguoiDung { get; set; }
    }
}
