//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newpro
    {
        public int maSP { get; set; }
        public string tenSP { get; set; }
        public decimal giaBan { get; set; }
        public string hinhAnh { get; set; }
    }
}
