//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkNguoiDung
    {
        public string Gmail { get; set; }
        public string tenDN { get; set; }
        public string PassSalt { get; set; }
        public string PassHash { get; set; }
    }
}
